### ISSUE TITLE
this is amazing

### ISSUE THREAD

**Issue by Yaheli003** [idodov/RedAlert#7]
first, thank you so much for this amazing project!

I've tried downloading via HACS but it didn't really work for me...
then I downloaded it manually and it worked. the problem is the sript is not running
when i do a full restart it shows the history but after a couple of seconds the script stops running

i'm not really good at coding... and it's probably something wrong that I did.
even even though I went and triple checked all the steps and tried it multiple times

**Comment by Yaheli003** [comment]
Hi, thank you for your quick response and support. I really appreciate it
I did had AppDaemon start on boot
And I've attached logs
![Screenshot_2](https://github.com/user-attachments/assets/457d71e5-af0f-4905-b778-da8182bcb5bf)

**Comment by idodov** [comment]
You need to create a folder called `www` inside the Home Assistant directory. After doing that, restart AppDaemon, and you should see that the error is resolved.

To ensure everything works smoothly, also add the following lines to `configuration.yaml` under the Home Assistant section:

```yaml
homeassistant:
  allowlist_external_urls:
    - http://192.168.86.20:8123  # YOUR HOME ASSISTANT IP
    - http://homeassistant.local:8123

  allowlist_external_dirs:
    - "/config/www"
```
